add getAll, find and changeName methods
mailersend/mailersend-php pull request #123
Opened 2024-04-18 12:31 UTC by Nyanko-sensei

resolves #2107

### Changelist

- [ ] Added a method to show all tokens `get all`
- [ ] Added a method to show single api token info `find`
- [ ] Added a method to change token name `changeName`

### Testing/QA

- Open deployed branch

### How to release

- none extra steps

### PR Checklist

- [ ] Tests are done and pass
- [ ] No PHP and JS errors
- [ ] PR does not go out of scope of the task
- [ ] Possible breaking changes are documented in the PR

### Screenshots

not applicable

### Risks

None  at this point

### Additional notes

It goes with other PR in docs and php-sdk

2024-04-19 08:00 UTC, fosron approved these changes

2024-04-22 10:07 UTC, JoaoFSCruz requested changes

2024-04-22 10:07 UTC, JoaoFSCruz commented on src/Endpoints/Token.php
> +        return $this->httpLayer->get(
This method is lacking the pagination parameters.

2024-04-22 10:07 UTC, JoaoFSCruz commented on README.md
> +        * [Find a tokens](#find-a-token )
```suggestion
        * [Find a token](#find-a-token)
```

2024-05-15 10:47 UTC, PeterOcansey reviewed
Just a few clean up

2024-05-15 10:47 UTC, PeterOcansey commented on README.md
> +        * [Find a tokens](#find-a-token)
Change to `Find a token`

2024-05-15 10:47 UTC, PeterOcansey commented on README.md
> +use MailerSend\Helpers\Builder\TokenParams;
Not used

2024-05-15 10:47 UTC, PeterOcansey commented on README.md
> +use MailerSend\Helpers\Builder\TokenParams;
Cleanup

2024-05-15 11:12 UTC, PeterOcansey approved these changes

2024-05-23 10:08 UTC, JoaoFSCruz approved these changes

2024-05-27 13:23 UTC, merged