Add manage invites endpoints
mailersend/mailersend-php pull request #124
Opened 2024-04-26 03:23 UTC by PeterOcansey

resolves #https://github.com/mailersend/mailersend/issues/6071

### Changelist

- [ ]Add list invite endpoint
- [ ] Add find invite endpoint
- [ ] Add resend invite endpoint
- [ ] Add cancel invite endpiont

2024-04-26 08:46 UTC, JoaoFSCruz requested changes

2024-04-26 08:46 UTC, JoaoFSCruz commented on src/Endpoints/Invite.php
> +    public function getAll(): array
This should have pagination.

2024-04-26 10:39 UTC, JoaoFSCruz approved these changes

2024-05-07 13:31 UTC, JoaoFSCruz commented
@PeterOcansey I think we can release this, right?

2024-05-09 13:12 UTC, PeterOcansey commented
@JoaoFSCruz I missed out README, I just updated it now....let me know if ok to release

2024-05-09 13:20 UTC, JoaoFSCruz approved these changes
My bad, also forgot about the README. Just a typo and we're good.

2024-05-09 13:20 UTC, JoaoFSCruz commented on README.md
> +        * [Cancel and Invite](#cancel-an-invite)
```suggestion
        * [Cancel an Invite](#cancel-an-invite)
```

2024-05-09 13:25 UTC, merged