Schedule messages
mailersend/mailersend-php pull request #42
Opened 2022-01-27 09:53 UTC by JoaoFSCruz

Related to [issue-2787](https://github.com/mailersend/mailersend/issues/2787).

Changelist:

- [x] Add endpoints
- [x] Add tests
- [x] Update changelog

2022-01-28 09:56 UTC, doobas requested changes

2022-01-28 09:56 UTC, doobas commented on src/Endpoints/ScheduleMessages.php
> +    public function getAll(?string $domainId = null, ?string $status = null, ?int $page = null, ?int $limit = Constants::DEFAULT_LIMIT): array
We need to add status constants into Constants.php for statuses and add validation for this field.

2022-01-28 10:52 UTC, doobas commented on README.md
> +<a name="scheduled-message"></a>
No link in the table of content to this example

2022-01-31 10:03 UTC, Agathe-Brusset approved these changes

2022-02-01 08:37 UTC, doobas approved these changes

2022-02-01 10:00 UTC, merged