hotfix/the set event and tags as array
mailersend/mailersend-php pull request #75
Opened 2023-01-30 09:28 UTC by yasir-alobaidi

make the set events and the set tags readable as arrays in the package, instead of reading it as non-array variable, which caused a syntax error while using the package in a Laravel project.

2023-02-01 11:57 UTC, PeterOcansey requested changes
I still get same validation error at my end.

2023-02-01 11:57 UTC, PeterOcansey commented on src/Helpers/BuildUri.php
>              $paramsArray[] = $key.'='.$value;
This does not work, it will end up generating `tags=dolorem&$key=lorem`,  assuming I pass ['dolorem', 'lorem']. tags should be an array.

2023-02-01 14:00 UTC, PeterOcansey commented
I think we can consider using `http_build_query` to build the params, it works better and will tidy up the code.

2023-02-01 14:10 UTC, yasir-alobaidi commented
I have tried this function but the result after decoding will give us the result as multidimensional array with its indexes, in this format it wont be proper in a URL.

2023-02-03 04:08 UTC, PeterOcansey requested changes
Not sure I get the explanation, I think `http_build_query` is designed to generate URL-encoded query string from associative (or indexed) array. [docs](https://www.php.net/manual/en/function.http-build-query.php)

```
$params = [
  'domain_id' => '3cct45',
  'date_from' => 1674691200000,
  'date_to' => 1675252800000,
  'tags' => ['tag1','tag2']
];

$queryString = http_build_query($params);
```
This should give us : `domain_id=3cct45&date_from=1674691200000&date_to=1675252800000&tags%5B0%5D=tag1&tags%5B1%5D=tag2 ` as the query string.

This works fine, at least from my test so far.

2023-02-03 04:10 UTC, PeterOcansey commented
@yasir-alobaidi Please did you test your solution? It doesn't seem to work for me.

2023-02-23 15:05 UTC, fosron commented
The PR is stale. If we don't get a response in the next week we will have to close it.

2023-03-16 15:03 UTC, closed without merging